all:
  vars:
    ansible_connection: ssh
    ansible_user: ansible
    ansible_become: true
    ansible_ssh_private_key_file: id_ed25519
    ansible_python_interpreter: /usr/bin/python3

  hosts:
    paris.zembla:
    milan.zembla:
    berlin.zembla:
