---
- name: Install some packages
  hosts: all
  tasks:

# Wait until host is ready
   - name: Wait for host {{inventory_hostname}} connection
     wait_for_connection:
    
# Upgrade all packages
   - name: upgrade all packages on CentOS/Fedora
     yum:
       name: "*"
       state: latest
     when: ansible_os_family == 'RedHat'
     register: result
     tags:
       - upgrade
   - debug:
       var: result.changed
     tags:
       - upgrade

# Upgrade all packages
   - name: update apt cache on Debian derivative
     apt:
       update_cache: yes
   - name: upgrade all packages on Debian derivative
     apt:
       name: "*"
       state: latest
     when: ansible_os_family == 'Debian'
     register: result
     tags:
       - upgrade
   - debug:
       var: result.changed
     tags:
       - upgrade

# Some useful packages for Debian
   - name: install bind-utils for Debian derivative
     package:
       name: bind9utils
       state: present
     when: ansible_os_family == 'Debian'


# Install for all distributions Debian/Redhat
   - name: install cockpit to monitor server
     package:
       name: cockpit
       state: present
   - name: install bash-completion 
     package:
       name: bash-completion
       state: present
   - name: install docker-compose
     package:
       name: docker-compose
       state: present

   - name: install wireguard-tools
     package:
       name: wireguard-tools
       state: present
   - name: install make
     package:
       name: make
       state: present

# Clone Reflow repo
   - name: Clone reflow-os repository
     git:
       repo: https://github.com/dyne/reflow-os
       dest: /root/reflow-os
       clone: yes
       update: yes

# Make ReflowOS
   - name: Make reflow-os config
     make:
       chdir: /root/reflow-os
       target: config
   - name: Make reflow-os setup
     make:
       chdir: /root/reflow-os
       target: setup
# TODO: BEGIN Current Caddyfile2 is copied from local (once fully functional, check in to repo)
   - name: Create config/deploy directory if it does not exist
     ansible.builtin.file:
       path: /root/reflow-os/bonfire/config/deploy
       state: directory
       mode: '0755'
#  - name: Create "Caddyfile" onto remote machine
#    ansible.builtin.copy:
#      src: Caddyfile2
#      dest: /root/reflow-os/bonfire/config/deploy/Caddyfile2
   - name: Create Caddyfile2 from template
     template:
       src: Caddyfile2.j2
       dest: /root/reflow-os/bonfire/config/deploy/Caddyfile2
# TODO: END Current Caddyfile2 is copied from local (once fully functional, check in to repo)
   - name: Make reflow-os bg
     make:
       chdir: /root/reflow-os
       target: bg

# Set timezone
   - name: set timezone
     timezone:
       name: Europe/Berlin

# Reboot when all things done
   - reboot:
       msg: "Reboot to finish setup."
       reboot_timeout: 60
     when: result.changed == "true"

